In [ ]:
import tensorflow as tf

In [ ]:
mnist=tf.keras.datasets.mnist


In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train,x_test=x_train/255.0,x_test/255.0

###### Buid tf.keras.Sequential by stacking up the layers

In [ ]:
model=tf.keras.models.Sequential([
      tf.keras.layers.Flatten(input_shape=(28,28)),
      tf.keras.layers.Dense(128,activation='relu'),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(10)               
])

In [ ]:
predictions=model(x_train[:1]).numpy()
predictions

array([[-0.28898704,  0.1648983 ,  0.09347114,  0.25297567, -0.35925278,
         0.44211102,  0.39015794,  0.1360673 ,  0.14482997,  0.0689163 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.06559736, 0.10327764, 0.09615811, 0.11278669, 0.06114633,
        0.13626938, 0.12937053, 0.10034256, 0.10122569, 0.09382571]],
      dtype=float32)

In [ ]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1],predictions).numpy()

1.9931216

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2930 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1410 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1064 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0873 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0751 - accuracy: 0.9759


In [ ]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0704 - accuracy: 0.9790


[0.0704205185174942, 0.9789999723434448]

In [ ]:
probability_model=tf.keras.Sequential([
     model,
     tf.keras.layers.Softmax()                                  
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.1067415e-08, 1.0138750e-08, 3.0410004e-06, 5.9779286e-05,
        2.2501046e-12, 1.1905326e-07, 2.4337682e-13, 9.9993634e-01,
        7.3009865e-08, 6.6360735e-07],
       [5.9468603e-09, 1.9631918e-04, 9.9974507e-01, 5.4690991e-05,
        1.4037012e-14, 6.5398569e-07, 8.6126249e-08, 3.9204593e-13,
        3.0875149e-06, 3.7863504e-11],
       [2.9948805e-07, 9.9881649e-01, 1.9654576e-04, 1.3555205e-05,
        2.7918288e-05, 8.6018281e-06, 4.1661962e-05, 5.3909421e-04,
        3.4974859e-04, 6.1591213e-06],
       [9.9973553e-01, 4.4300581e-09, 1.5233101e-04, 5.1639958e-08,
        7.3213181e-07, 1.5293755e-06, 8.7439723e-05, 4.4411900e-06,
        6.9704112e-07, 1.7213863e-05],
       [1.5333744e-06, 1.4735213e-06, 1.9574647e-05, 5.3053867e-08,
        9.9705446e-01, 8.3591988e-07, 3.7028351e-06, 1.1487517e-05,
        1.0031880e-06, 2.9057474e-03]], dtype=float32)>